'use client';

import LegalPage, { Section, useLegalLang, COMPANY, SITE, CONTACT_EMAIL } from '@/components/LegalPage';

const C = {
  es: {
    title: 'Declaración de cumplimiento 18 U.S.C. § 2257',
    s: [
      ['Verificación de edad y consentimiento', [
        `Todo el contenido disponible a través de ${SITE} se genera mediante inteligencia artificial a partir de la imagen de personas que: (1) acreditaron ser mayores de 18 años mediante documento de identidad oficial verificado; y (2) firmaron un consentimiento explícito para la creación y el uso de su modelo digital. No se crea ningún contenido a partir de la imagen de personas no verificadas.`,
      ]],
      ['Registros', [
        `${COMPANY} mantiene registros de verificación de edad y consentimiento de todas las personas cuya imagen se utiliza en el Servicio, conforme a las prácticas de mantenimiento de registros aplicables. Custodio de registros: ${COMPANY} — solicitudes de inspección: ${CONTACT_EMAIL}.`,
      ]],
      ['Tolerancia cero', [
        'Tenemos tolerancia cero con cualquier contenido que involucre o aparente involucrar a menores. Cualquier intento de solicitar dicho contenido se rechaza, la cuenta se termina y el caso se reporta a las autoridades competentes (incl. NCMEC cuando corresponde).',
      ]],
    ],
  },
  en: {
    title: '18 U.S.C. § 2257 Compliance Statement',
    s: [
      ['Age verification and consent', [
        `All content available through ${SITE} is generated by artificial intelligence from the likeness of individuals who: (1) proved they are over 18 years of age through a verified government-issued ID; and (2) signed explicit consent for the creation and use of their digital model. No content is ever created from the likeness of unverified individuals.`,
      ]],
      ['Records', [
        `${COMPANY} maintains age-verification and consent records for all individuals whose likeness is used in the Service, in line with applicable record-keeping practices. Records custodian: ${COMPANY} — inspection requests: ${CONTACT_EMAIL}.`,
      ]],
      ['Zero tolerance', [
        'We have zero tolerance for any content involving or appearing to involve minors. Any attempt to request such content is rejected, the account is terminated, and the case is reported to the competent authorities (including NCMEC where applicable).',
      ]],
    ],
  },
};

export default function Usc2257Page() {
  const l = useLegalLang();
  const c = C[l];
  return (
    <LegalPage title={c.title}>
      {c.s.map(([h, ps]) => (
        <Section key={h} h={h}>{ps.map((p, i) => <p key={i}>{p}</p>)}</Section>
      ))}
    </LegalPage>
  );
}
